### ISSUE TITLE
Scope and naming of the Element

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-deeplabcut#1]
The primary use-case for this element is managing DeepLabCut workflows with DataJoint, but it could also be expanded to include other continuous streams of behavioral data, such as treadmill information.
1. Should the element expand to include treadmill data? Other forms of data?
2. If not, and the primary focus is to be DeepLabCut, should the Element be renamed `element-dlc`? While this might be more transparent, it breaks the trend across other elements to be tool-generic.

**Comment by CBroz1** [comment]
`element-free-behavior` was discussed to set the scope to ingesting continuous behavior.

**Comment by dimitri-yatsenko** [comment]
Treadmill, eye movements, whisking, and licks are much simpler and I would not mix them with ML-based frameworks for free behavior analysis. The scale and complexity of the analysis is just too different.

Rather than designing one element to accommodate everything, it is typically more practical to design an element that does one thing really well.

**Comment by dimitri-yatsenko** [comment]
I think the element will make much more sense for people and will be more findable in search engines, if it is very specific, e.g. `element-deeplabcut` only doing DeepLabCut very well.  If we need to add JAABA, we can add a more general element later.
